### ISSUE TITLE
layout 5 belangrijkste acties

### ISSUE THREAD

**Issue by bert-packed** [PACKED-vzw/scoremodel#18]
proposal for layout:
title of the corresponding section in normal heading (so without highlight in blue)
remove the labels for the ja/nee answer and DSA

The answer is obviously always no, and DSA is not relevant here.

**Comment by pieterdp** [comment]
Removed the answer labels; kept the <benchmark> label as I think it is relevant to see which benchmark(s) tag the question as important.
I think highlighting the sections serves a purpose, because the order of the questions is essentially random if `q1.value == q2.value`, so questions are not grouped per section.
